trigger:
- objetivo-6

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Install Docker'

- script: |
    docker pull javigp2002/lazyfood:latest
    docker run javigp2002/lazyfood:latest deno task test
  displayName: 'Run Deno task'
